# permissions for end users to view dnsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsconfig-viewer-role
rules:
- apiGroups:
  - domain-config.cmit.com
  resources:
  - dnsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - domain-config.cmit.com
  resources:
  - dnsconfigs/status
  verbs:
  - get
