
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - domain-config.cmit.com
  resources:
  - dnsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - domain-config.cmit.com
  resources:
  - dnsconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - domain-config.cmit.com
  resources:
  - dnsconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - domain-config.cmit.com
  resources:
  - initetcds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - domain-config.cmit.com
  resources:
  - initetcds/finalizers
  verbs:
  - update
- apiGroups:
  - domain-config.cmit.com
  resources:
  - initetcds/status
  verbs:
  - get
  - patch
  - update
